/*
 * This source file was generated by the Gradle 'init' task
 */
package com.edwardp20.cococalc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class CocoTest {
    @Test void appHasAGreeting() {
        Coco classUnderTest = new Coco();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
